name: Feature Flags ci/cd flow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up virtualenv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt    

      - name: Start app in background
        run: |
          source venv/bin/activate
          nohup python app.py > app.log 2>&1 &
    
      - name: Run Unit Test
        run: |
          status=$(
            curl \
              --retry 5 \
              --retry-delay 2 \
              --retry-connrefused \
              --silent \
              --write-out "%{http_code}" \
              --output /dev/null \
              http://localhost:5000/flags
          )
          test "$status" -eq 200 \
            && echo "App is up" \
            || (echo "Unexpected status: $status" && exit 1)

  e2e_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run docker compose up
        env:
          # MONGO_HOST: "db" # service name in docker-compose.yaml
          MONGO_INITDB_DATABASE: ${{ env.MONGO_INITDB_DATABASE }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} 
        run: docker compose -f docker-compose.yaml up -d --wait --build

      - name: Verify containers
        run: docker ps -a

      - name: Run E2E Test
        run: |
          set -o errexit -o pipefail
          response=$(curl --fail --silent http://localhost/flags)
               
          echo "$response" | jq -e 'type == "array"' > /dev/null || {
            echo "Response is not an array"
            exit 1
          }
          
          echo "$response" | jq -e 'length > 0' > /dev/null || {
            echo "No feature flags found"
            exit 1
          }
          
          echo "$response" | jq -e '.[0] | has("_id") and has("name") and has("environments")' > /dev/null || {
            echo "First flag missing required keys"
            exit 1
          }
          echo "E2E test passed"

      - name: Save Docker image to file
        run: docker save ff-service -o ff-service.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ff-service.tar

  version:
    needs: [unit_test, e2e_test]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.new_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: "1.0.0"
          DEFAULT_BUMP: "patch"
          FORCE_WITHOUT_CHANGES: "true"
          WITH_V: true

  publish:
    env:
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      ECR_REPO: ${{ vars.ECR_REPO }}
      GHCR: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
    needs: version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
         name: docker-image

      - name: Load Docker image
        run: docker load -i ff-service.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Authenticate Docker to ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Tag Docker image for ECR
        run: |
          docker tag ff-service $ECR_REGISTRY/$ECR_REPO:latest
          docker tag ff-service $ECR_REGISTRY/$ECR_REPO:${{ needs.version.outputs.image_tag }}

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO:latest
          docker push $ECR_REGISTRY/$ECR_REPO:${{ needs.version.outputs.image_tag }}
       
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Tag for GHCR
        run: |
          docker tag feature-flags-api:${{ github.sha }} $GHCR/feature-flags-api:latest
          docker tag feature-flags-api:${{ github.sha }} $GHCR/feature-flags-api:${{ needs.version.outputs.image_tag }}
      
      - name: Push to GHCR
        run: |
          docker push $GHCR/feature-flags-api:latest
          docker push $GHCR/feature-flags-api:${{ needs.version.outputs.image_tag }}