name: Feature Flags CI Pipeline

on:
  pull_request:
    branches: [ main, dev, staging ]
    paths-ignore:
    - 'frontend/**'
    - '**.md'
jobs:
  run-tests:
    uses: ./.github/workflows/reusable-tests.yaml
    secrets: inherit # Pass all secrets to the called workflow (future-proofing)
 