name: Feature Flags CI/CD

on:
  pull_request:
    branches:
      - main
      - dev
      - staging
    paths-ignore:
      - 'frontend/**'
      - '**.md'

  push:
    branches:
      - 'feature/**'
      - 'dev'
      - 'staging'
      - 'main'
    paths-ignore:
      - 'frontend/**'
      - '**.md'

  workflow_dispatch:

jobs:

  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up virtualenv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt    

      - name: Start app in background
        run: |
          source venv/bin/activate
          nohup python app.py > app.log 2>&1 &
    
      - name: Run Unit Test
        run: |
          status=$(
            curl \
              --retry 5 \
              --retry-delay 2 \
              --retry-connrefused \
              --silent \
              --write-out "%{http_code}" \
              --output /dev/null \
              http://localhost:5000/flags
          )
          test "$status" -eq 200 \
            && echo "App is up" \
            || (echo "Unexpected status: $status" && exit 1)

  e2e_test:
    needs: [unit_test]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run docker compose up
        env:
          MONGO_INITDB_ROOT_USERNAME: test-admin
          MONGO_INITDB_ROOT_PASSWORD: test-password
        run: docker compose -f docker-compose.local.yaml up -d --wait --build

      - name: Verify containers
        run: docker ps -a

      - name: Run E2E Test
        run: |
          set -o errexit -o pipefail
          response=$(curl --fail --silent http://localhost/flags)
               
          echo "$response" | jq -e 'type == "array"' > /dev/null || {
            echo "Response is not an array"
            exit 1
          }
          
          echo "$response" | jq -e 'length > 0' > /dev/null || {
            echo "No feature flags found"
            exit 1
          }
          
          echo "$response" | jq -e '.[0] | has("_id") and has("name") and has("environments")' > /dev/null || {
            echo "First flag missing required keys"
            exit 1
          }
          echo "E2E test passed"

      ## Commented out artifact step due to free tier storage limits,
      ## Left here for demonstration purposes    
      # - name: Save Docker image to file
      #   run: docker save feature-flags-api -o feature-flags-api.tar

      # - name: Upload image artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker-image
      #     path: feature-flags-api.tar

  version:
    needs: [unit_test, e2e_test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump version and push tag(Main branch only)
        if: github.ref == 'refs/heads/main'
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: "1.0.0"
          DEFAULT_BUMP: "patch"
          FORCE_WITHOUT_CHANGES: "true"
          WITH_V: true

      # Calculate the Image Tag for all branches
      - name: Calculate Image Tag
        id: set_tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=${{ steps.version.outputs.new_tag }}" >> $GITHUB_OUTPUT
            
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "tag=rc-${SHORT_SHA}" >> $GITHUB_OUTPUT
            
          else
            echo "tag=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

  publish:
    env:
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      ECR_REPO: ${{ vars.ECR_REPO }}
      GHCR: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TAG: ${{ needs.version.outputs.image_tag }}

    needs: version
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')    
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write # for OIDC
      contents: read
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      ## Commented out artifact step due to free tier storage limits,
      ## Left here for demonstration purposes
      # - name: Download image artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #    name: docker-image

      # - name: Load Docker image
      #   run: docker load -i feature-flags-api.tar

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate Docker to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker image for ECR & GHCR
        run: |
          set -euo pipefail
       
          docker compose -f docker-compose.local.yaml build && \
          docker tag feature-flags-api:latest feature-flags-api:$TAG 

      - name: Tag Docker image for ECR
        run: |
          docker tag feature-flags-api:$TAG $ECR_REGISTRY/$ECR_REPO:$TAG

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag feature-flags-api:$TAG $ECR_REGISTRY/$ECR_REPO:latest
          fi

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO:$TAG

          ## push latest tag only if on main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker push $ECR_REGISTRY/$ECR_REPO:latest
          fi
       
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Tag for GHCR
        run: |
          docker tag feature-flags-api:$TAG $GHCR/feature-flags-api:$TAG

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              docker tag feature-flags-api:$TAG $GHCR/feature-flags-api:latest
            fi
      
      - name: Push to GHCR
        run: |
          docker push $GHCR/feature-flags-api:$TAG

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker push $GHCR/feature-flags-api:latest
          fi
