name: Terraform

on: 
  workflow_dispatch:
    inputs:
      env:
        description: "Terraform environment (workspace)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for OIDC
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: shaarron/feature-flags-infrastructure
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869432184848:role/gha-oidc-deploy
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="backend.hcl" -backend-config="key=state/${{ github.event.inputs.env }}/terraform.tfstate"

      - name: Terraform Workspace Select
        run: terraform workspace select ${{ github.event.inputs.env }} || terraform workspace new ${{ github.event.inputs.env }}

      - name: Terraform Plan
        run: terraform plan -var-file="../workspaces/${{ github.event.inputs.env }}.tfvars"

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -var-file="../workspaces/${{ github.event.inputs.env }}.tfvars"